config/routes.rb
Rails.application.routes.draw do
  resources :whispers
  
  get '/', to: 'whispers#top'
  get '/top', to: 'whispers#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/whisper.rb
class Whisper < ApplicationRecord
  validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/whispers_controller.rb
class WhispersController < ApplicationController
  before_action :set_whisper, only: [:show, :edit, :update, :destroy]

  def top
  end
  
  def index
    @whispers = Whisper.all
  end

  def show
  end

  def new
    @whisper = Whisper.new
  end

  def edit
  end

  def create
    @whisper = Whisper.new(whisper_params)

    respond_to do |format|
      if @whisper.save
        format.html { redirect_to @whisper, notice: 'Whisper was successfully created.' }
        format.json { render :show, status: :created, location: @whisper }
      else
        format.html { render :new }
        format.json { render json: @whisper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @whisper.update(whisper_params)
        format.html { redirect_to @whisper, notice: 'Whisper was successfully updated.' }
        format.json { render :show, status: :ok, location: @whisper }
      else
        format.html { render :edit }
        format.json { render json: @whisper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @whisper.destroy
    respond_to do |format|
      format.html { redirect_to whispers_url, notice: 'Whisper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_whisper
    @whisper = Whisper.find(params[:id])
  end

  def whisper_params
    params.require(:whisper).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneTw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/whispers/_footer.html.erb
<footer>
  <p>COPYRIGHT © kodatakasi ALL RIGHTS RESERVED.</p>
</footer>

app/views/whispers/_form.html.erb
<%= form_with(model: whisper, local: true) do |form| %>
  <% if @whisper.errors.any?%>
    <div id="error_explanetion">
      <h2><%= @whisper.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @whisper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/whispers/_header.html.erb
<header>
  <h1 class="title">Whispers</h1>
</header>

app/views/whispers/edit.html.erb
<%= render 'header' %>

<h1>編集</h1>

<%= render 'form', whisper: @whisper %>

<%= link_to 'つぶやき', @whisper %> |
<%= link_to '戻る', whispers_path %>

<%= render 'footer' %>

app/views/whispers/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'header' %>

<table>
  <thead>
    <tr>
      <th>つぶやき</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @whispers.each do |whisper| %>
      <tr>
        <td class="content"><%= whisper.content %></td>
        <td><%= link_to 'つぶやき', whisper %></td>
        <td><%= link_to '編集', edit_whisper_path(whisper) %></td>
        <td><%= link_to '削除', whisper, method: :delete, data: { confirm: '削除してもいいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'つぶやく', new_whisper_path %>
<%= link_to 'TOP', top_path %>
<%= render 'footer' %>

app/views/whispers/new.html.erb
<%= render 'header' %>

<h1>つぶやく</h1>

<%= render 'form', whisper: @whisper %>

<%= link_to '戻る', whispers_path %>

<%= render 'footer' %>

app/views/whispers/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'header' %>

<p>
  <strong>内容:</strong>
  <%= @whisper.content %>
</p>

<%= link_to '編集', edit_whisper_path(@whisper) %> |
<%= link_to '戻る', whispers_path %>

<%= render 'footer' %>

app/views/whispers/top.html.erb
<%= render 'header' %>
<div class="top">
  <h1>DIVE INTO CODEのTwitterクローンを作ろう課題です。</h1>
  <%= link_to "つぶやいてみる", whispers_path, class: 'btn btn-square' %>
</div>

<%= render 'footer' %>